apiVersion: v1
kind: Service
metadata:
  name: random
  labels:
    app: random
spec:
  ports:
    - protocol: TCP
      targetPort: 8080
      port: 8080
      nodePort: 30005
  selector:
    app: random
  type: NodePort

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: random
  name: random
spec:
  replicas: 1
  selector:
    matchLabels:
      app: random
  template:
    metadata:
      labels:
        app: random
    spec:
      containers:
        - image: shahincsejnu/httpapiserver:v1.0.5
          imagePullPolicy: Always
          name: random
          ports:
            - containerPort: 8080
              protocol: TCP
      restartPolicy: Always
