apiVersion: v1
kind: Pod
metadata:
  name: pod-using-secret-as-env
spec:
  containers:
    - name: container-using-secret-as-env
      image: redis
      env:
        - name: SECRET_USERNAME
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: username
        - name: SECRET_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: password

