apiVersion: v1
kind: Pod
metadata:
  name: lifecycle-demo
spec:
  containers:
    - name: lifecycle-demo-container
      image: nginx
      lifecycle:
        postStart:
          exec:
            command: ["/bin/sh", "-c", "echo Hello from the postStart handler > abc.txt"]
            # `kubectl exec -it lifecycle-demo -- cat abc.txt` to see the message
        preStop:
          exec:
            command: ["/usr/sbin/nginx", "-s", "quit"]