apiVersion: v1
kind: Pod
metadata:
  name: test-ed
spec:
  containers:
    - image: shahincsejnu/httpapiserver:v1.0.6
      name: test-container
      volumeMounts:
        - name: cache-volume
          mountPath: /test
    - image: nginx
      name: test-container2
      volumeMounts:
        - name: cache-volume
          mountPath: /test2
  volumes:
    - name: cache-volume
      emptyDir: {}
